# LIBRERIAS SELENIUM...

from selenium import webdriver  # Basico de webdriver...

# Para los selectores...(By.XPATH,"//input[@id='userEmail']")
from selenium.webdriver.common.by import By

# Agregar funciones...Keys.TAB + Keys.ENTER.  Etc...
from selenium.webdriver.common.keys import Keys

import time  # Tiempo...

# Agregar condiciones... .until(EC.element_to_be_clickable)
from selenium.webdriver.support import expected_conditions as EC

# Implicit & Explicit...
from selenium.webdriver.support.wait import WebDriverWait

# Para seleccionar checkbox poor index, por valor y por texto, pero el mas confiable es el index...
from selenium.webdriver.support.ui import Select

from selenium.common.exceptions import TimeoutException  # try - Catch...
